version: "3.9"

services:
  vice-versa-api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: viceversa_package
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
    networks:
      - vice-versa-network

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      - vice-versa-network

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vive-versa-frontend
    depends_on:
      - vice-versa-api
    networks:
      - vice-versa-network

  nginx:
    restart: always
    depends_on:
      - vice-versa-api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - vice-versa-network

networks:
  vice-versa-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
