version: "3.9"

services:
  vice-versa-api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: viceversa_package
    volumes:
      - /app/node_modules
      - ./server:/app
    # ports:
    #   - 5000:5000
    depends_on:
      - mongo
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
    networks:
      - vice-versa-network

  mongo:
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - vice-versa-network

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: thisIsIt4you
    volumes:
      - mongodb-data:/data/db
    networks:
      - vice-versa-network

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: vive-versa-frontend
    volumes:
      - ./client/node_modules:/app/node_modules
      - ./client:/app
    # ports:
    #   - 3000:3000
    depends_on:
      - vice-versa-api
    networks:
      - vice-versa-network

  nginx:
    restart: always
    depends_on:
      - vice-versa-api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    networks:
      - vice-versa-network

networks:
  vice-versa-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
