name: vice-versa-package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Docker-compose
      run: |
        docker-compose -f docker-compose.yml up --build
